export default function Content(){
    return `    
    <div id="content">

    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>
    <h1>OIUYTREWSDFGHJKMNBVFDS</h1>

    </div>
    `;
}